version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/ci-cd-demo-server
    overwrite: yes
permissions:
  - object:  /home/ec2-user/ci-cd-demo-server
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root