# This is a basic workflow to help you get started with Actions
name: gradle CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: main
  pull_request:
    branches: main
    
env:
  DEPLOY_ZIP_FILE: ci-cd-demo.zip

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ./gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew build

      - name: aws 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Zip 파일 생성
        run: |
          mkdir -p before-deploy/
          cp appspec.yml before-deploy/
          cp scripts/*.sh before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r before-deploy *
          cd ../ && mkdir -p deploy
          mv before-deploy/before-deploy.zip deploy/$DEPLOY_ZIP_FILE

      - name: S3 업로드
        run: aws s3 cp --region ap-northeast-2 ./deploy/$DEPLOY_ZIP_FILE s3://ci-cd-demo-bucket/server/build.zip
     
      - name: code deploy
        run: aws deploy create-deployment --application-name ci-cd-demo-codedeploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ci-cd-deploy-group --s3-location bucket=ci-cd-demo-bucket,bundleType=zip,key=server/build.zip
